Homework
Zelderon7/Praktika10 pull request #1
Opened 2023-07-05 06:23 UTC by Zelderon7

Merging master and homework

2023-07-06 09:24 UTC, Evgeni-Georgiev requested changes
Good job.

2023-07-06 09:24 UTC, Evgeni-Georgiev commented on src/main/java/org/example/hw2.java
> +
Remove unnecessary line.

2023-07-06 09:24 UTC, Evgeni-Georgiev commented on src/main/java/org/example/hw2.java
> +
Remove unnecessary line.

2023-07-06 09:24 UTC, Evgeni-Georgiev commented on src/main/java/org/example/zad2.java
> +    public static void main(String[] args) {
Add new line after the method. After: public static void main(String[] args) {.

2023-07-06 09:24 UTC, Evgeni-Georgiev commented on src/main/java/org/example/zad2.java
> +
Remove unnecessary line.

2023-07-06 09:24 UTC, Evgeni-Georgiev commented on src/main/java/org/example/zad3.java
> +    static Scanner in = new Scanner(System.in);
Add new line after the variable. Add new line after "static Scanner in = new Scanner(System.in);".

2023-07-06 09:24 UTC, Evgeni-Georgiev commented on src/main/java/org/example/zad5.java
> +public class zad5 {
Smart solution. :)

2023-07-06 09:24 UTC, Evgeni-Georgiev commented on src/main/java/org/example/zad3.java
> +        int w = getInt(50, 500);
The variable and method are not explaining what they are doing. Be more descriptive.

2023-07-06 09:24 UTC, Evgeni-Georgiev commented on src/main/java/org/example/zad3.java
> +        while (a < min || a >= max){
Add space between ) and {.

2023-07-06 09:24 UTC, Evgeni-Georgiev commented on src/main/java/org/example/zad3.java
> +    private static int getInt(int min, int max){
Add space between ) and {.

2023-07-11 06:12 UTC, intro-java approved these changes

2023-07-11 06:13 UTC, Evgeni-Georgiev approved these changes

2023-07-12 05:59 UTC, merged